- name: install docker-registry
  apt: state=present update_cache=yes cache_valid_time=86400 name=docker-registry

- name: configure docker-registry listener
  copy: dest=/etc/default/docker-registry owner=root group=root mode=0644 content='DOCKER_REGISTRY_LISTEN="{{ tsuru_docker_registry_listen }}"'
  notify:
    - restart docker-registry

- name: start docker-registry
  service: state=started name=docker-registry
