- name: import redis ppa gpg key
  apt_key: keyserver=keyserver.ubuntu.com id=136221EE520DDFAF0A905689B9316A7BC7917B12

- name: add redis repository
  apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes

- name: install redis
  apt: state=latest name=redis-server update_cache=yes

- name: start redis
  service: state=started name=redis-server
